#!/bin/bash

# record file
file="/home/markchang/.queue"

while [ $(wc -l $file | awk '{print $1}') -gt "0" ] ; do
	pop_data=$(head -n 1 $file)
	echo $pop_data
	tail -n +2 $file | sponge $file
	# YOUR Command Here
done
